name: llama
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.9
  - pytorch==1.12.1
  - yapf==0.33.0
  - pylint==2.17.4
  - pip==23.2.1
  - pip:
    - azure-identity==1.13.0
    - azure-mgmt-cognitiveservices==13.4.0
    - azure-ai-ml==1.8.0
    - azure-mgmt-msi==7.0.0
    - azure-mgmt-authorization==3.0.0